apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: amjs-test
  description: AMJS  App
  tags:
    - javascript
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=amjs-test,tier=frontend'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://yelb-ui.example.com
      title: 'amjs test information'
      icon: locallibrary
spec:
  type: service
  lifecycle: experimental
  owner: tas-dev-ex
  system: amjs-test-space
  dependsOn: [Component:amjs-test-api-app]
